//! Behavioral tests for the ReadStat DTA ingestion spike.
//!
//! Fixtures:
//! * `patients.dta` — byte-for-byte the Python oracle's `sample_dta`
//!   (pandas `to_stata`), used to cross-check against the Python backend.
//! * `labeled.dta` — generated by `fixtures/generate_labeled_dta.c` with the
//!   ReadStat writer; exercises variable labels, numeric and string value
//!   labels, system missing, and tagged missing (.a / .b).

use std::path::{Path, PathBuf};

use tabdat_readstat_spike::{DtaValue, parse_dta};

fn fixture(name: &str) -> PathBuf {
  Path::new(env!("CARGO_MANIFEST_DIR"))
    .join("fixtures")
    .join(name)
}

#[test]
fn parses_oracle_patients_fixture() {
  let dataset = parse_dta(&fixture("patients.dta")).expect("patients.dta parses");

  assert_eq!(dataset.metadata.row_count, 3);
  assert_eq!(dataset.metadata.var_count, 4);
  assert_eq!(
    dataset
      .variables
      .iter()
      .map(|v| v.name.as_str())
      .collect::<Vec<_>>(),
    ["age", "bmi", "sex", "cost"]
  );
  assert_eq!(dataset.rows.len(), 3);
  assert!(dataset.rows.iter().all(|row| row.len() == 4));

  // age: int32 30/42/54
  assert_eq!(dataset.rows[0][0], DtaValue::Int32(30));
  assert_eq!(dataset.rows[1][0], DtaValue::Int32(42));
  assert_eq!(dataset.rows[2][0], DtaValue::Int32(54));
  // bmi: double 22.5/25.0/27.5
  assert_eq!(dataset.rows[0][1], DtaValue::Double(22.5));
  assert_eq!(dataset.rows[1][1], DtaValue::Double(25.0));
  assert_eq!(dataset.rows[2][1], DtaValue::Double(27.5));
  // sex: string F/M/F
  assert_eq!(dataset.rows[0][2], DtaValue::String("F".into()));
  assert_eq!(dataset.rows[1][2], DtaValue::String("M".into()));
  assert_eq!(dataset.rows[2][2], DtaValue::String("F".into()));
  // cost: 100.0/150.0/system missing
  assert_eq!(dataset.rows[0][3], DtaValue::Double(100.0));
  assert_eq!(dataset.rows[1][3], DtaValue::Double(150.0));
  assert_eq!(dataset.rows[2][3], DtaValue::SystemMissing);
  assert!(dataset.rows[2][3].is_missing());
}

#[test]
fn preserves_variable_labels_and_types() {
  let dataset = parse_dta(&fixture("labeled.dta")).expect("labeled.dta parses");

  assert_eq!(dataset.metadata.row_count, 4);
  assert_eq!(dataset.metadata.var_count, 5);
  assert_eq!(
    dataset.metadata.file_label.as_deref(),
    Some("TabDat ReadStat spike fixture")
  );

  let by_name: std::collections::HashMap<&str, &tabdat_readstat_spike::DtaVariable> = dataset
    .variables
    .iter()
    .map(|v| (v.name.as_str(), v))
    .collect();

  assert_eq!(by_name["id"].label.as_deref(), Some("Subject ID"));
  assert_eq!(by_name["age"].label.as_deref(), Some("Age in years"));
  assert_eq!(by_name["band"].label.as_deref(), Some("Income band"));
  assert_eq!(by_name["sex"].label.as_deref(), Some("Sex"));
  assert_eq!(by_name["score"].label.as_deref(), Some("Test score"));

  // Storage types survive the round trip.
  assert!(matches!(
    by_name["id"].type_,
    tabdat_readstat_spike::DtaType::Int32
  ));
  assert!(matches!(
    by_name["age"].type_,
    tabdat_readstat_spike::DtaType::Float
  ));
  assert!(matches!(
    by_name["score"].type_,
    tabdat_readstat_spike::DtaType::Double
  ));
  assert!(matches!(
    by_name["sex"].type_,
    tabdat_readstat_spike::DtaType::String
  ));
}

#[test]
fn preserves_value_label_sets() {
  let dataset = parse_dta(&fixture("labeled.dta")).expect("labeled.dta parses");

  let bands = dataset
    .label_sets
    .iter()
    .find(|set| set.name == "income_band")
    .expect("income_band label set present");
  assert_eq!(bands.labels.len(), 3);
  assert_eq!(bands.labels[0].value, DtaValue::Int32(1));
  assert_eq!(bands.labels[0].label, "low");
  assert_eq!(bands.labels[1].value, DtaValue::Int32(2));
  assert_eq!(bands.labels[1].label, "mid");
  assert_eq!(bands.labels[2].value, DtaValue::Int32(3));
  assert_eq!(bands.labels[2].label, "high");

  let sexes = dataset
    .label_sets
    .iter()
    .find(|set| set.name == "sex_label")
    .expect("sex_label label set present");
  assert_eq!(sexes.labels.len(), 2);
  // ReadStat does not persist string value-label keys: the writer stores 0 for
  // every string key and the reader delivers that raw int32. The label texts
  // are correct; the keys are not usable. (Documented ReadStat limitation.)
  assert_eq!(sexes.labels[0].value, DtaValue::Int32(0));
  assert_eq!(sexes.labels[0].label, "Male");
  assert_eq!(sexes.labels[1].value, DtaValue::Int32(0));
  assert_eq!(sexes.labels[1].label, "Female");

  // Variables reference their label sets by name.
  let by_name: std::collections::HashMap<&str, &tabdat_readstat_spike::DtaVariable> = dataset
    .variables
    .iter()
    .map(|v| (v.name.as_str(), v))
    .collect();
  assert_eq!(by_name["band"].label_set.as_deref(), Some("income_band"));
  assert_eq!(by_name["sex"].label_set.as_deref(), Some("sex_label"));
  assert_eq!(by_name["id"].label_set, None);
}

#[test]
fn classifies_system_and_tagged_missing() {
  let dataset = parse_dta(&fixture("labeled.dta")).expect("labeled.dta parses");

  // score column is index 4.
  assert_eq!(dataset.rows[0][4], DtaValue::Double(88.25));
  assert_eq!(dataset.rows[1][4], DtaValue::TaggedMissing('a'));
  assert_eq!(dataset.rows[2][4], DtaValue::SystemMissing);
  assert_eq!(dataset.rows[3][4], DtaValue::TaggedMissing('b'));

  assert!(!dataset.rows[0][4].is_missing());
  assert!(dataset.rows[1][4].is_missing());
  assert!(dataset.rows[2][4].is_missing());
  assert!(dataset.rows[3][4].is_missing());

  // Missing string on sex (index 3) in row 3. ReadStat delivers missing
  // strings as empty strings, not as system missing (a documented ReadStat
  // behavior); TabDat must treat an empty string as missing for string vars.
  assert_eq!(dataset.rows[2][3], DtaValue::String(String::new()));
  // An empty string is not classified as missing by DtaValue::is_missing; that
  // interpretation is a TabDat data-semantics decision, not a ReadStat one.
  assert!(!dataset.rows[2][3].is_missing());
}

#[test]
fn rejects_missing_file() {
  let error = parse_dta(&fixture("does-not-exist.dta")).unwrap_err();
  assert!(matches!(
    error,
    tabdat_readstat_spike::DtaError::Native { .. }
  ));
}

#[test]
fn rejects_corrupt_file() {
  let path = fixture("corrupt.dta");
  std::fs::write(&path, b"this is not a stata dataset at all").expect("write corrupt fixture");
  let error = parse_dta(&path).unwrap_err();
  let _ = std::fs::remove_file(&path);
  assert!(matches!(
    error,
    tabdat_readstat_spike::DtaError::Native { .. }
  ));
}

#[test]
fn repeated_parse_and_teardown_is_stable() {
  // Allocation/free churn: parse the same file repeatedly to surface leaks or
  // double-free behavior in the parser teardown path.
  for _ in 0..50 {
    let dataset = parse_dta(&fixture("labeled.dta")).expect("repeated parse succeeds");
    assert_eq!(dataset.rows.len(), 4);
  }
}
