//! Canonical in-application help topics for TabDat.

pub const AVAILABLE_HELP_TOPICS: &[&str] = &[
  "append",
  "assert",
  "bar",
  "bayes",
  "bayes_prefix",
  "bayesplot",
  "by",
  "cfregress",
  "codebook",
  "collapse",
  "count",
  "cvelasticnet",
  "cvlasso",
  "cvridge",
  "datasignature",
  "decode",
  "describe",
  "did",
  "dml",
  "doctor",
  "drdid",
  "drop",
  "duplicates",
  "elasticnet",
  "encode",
  "estat",
  "estat_report",
  "exit",
  "export",
  "generate",
  "gsort",
  "head",
  "heckman",
  "histogram",
  "isid",
  "ivregress",
  "join",
  "keep",
  "label",
  "lasso",
  "logit",
  "lowess",
  "missing",
  "nbreg",
  "nl",
  "panel",
  "poisson",
  "postlasso",
  "predict",
  "probit",
  "qreg",
  "quit",
  "recode",
  "regress",
  "rename",
  "replace",
  "reshape",
  "ridge",
  "run",
  "save",
  "scatter",
  "select",
  "set",
  "sort",
  "spregress",
  "sql",
  "status",
  "streg",
  "summarize",
  "tabulate",
  "tail",
  "tobit",
  "use",
  "xtabond",
  "xtdata",
  "xtlogit",
  "xtreg",
  "zinb",
  "zip",
];

pub fn available_help_topics() -> &'static [&'static str] {
  AVAILABLE_HELP_TOPICS
}

pub fn load_help_topic_text(topic: &str) -> Option<&'static str> {
  match topic {
    "append" => Some(include_str!("help/topics/append.md")),
    "assert" => Some(include_str!("help/topics/assert.md")),
    "bar" => Some(include_str!("help/topics/bar.md")),
    "bayes" => Some(include_str!("help/topics/bayes.md")),
    "bayes_prefix" => Some(include_str!("help/topics/bayes_prefix.md")),
    "bayesplot" => Some(include_str!("help/topics/bayesplot.md")),
    "by" => Some(include_str!("help/topics/by.md")),
    "cfregress" => Some(include_str!("help/topics/cfregress.md")),
    "codebook" => Some(include_str!("help/topics/codebook.md")),
    "collapse" => Some(include_str!("help/topics/collapse.md")),
    "count" => Some(include_str!("help/topics/count.md")),
    "cvelasticnet" => Some(include_str!("help/topics/cvelasticnet.md")),
    "cvlasso" => Some(include_str!("help/topics/cvlasso.md")),
    "cvridge" => Some(include_str!("help/topics/cvridge.md")),
    "datasignature" => Some(include_str!("help/topics/datasignature.md")),
    "decode" => Some(include_str!("help/topics/decode.md")),
    "describe" => Some(include_str!("help/topics/describe.md")),
    "did" => Some(include_str!("help/topics/did.md")),
    "dml" => Some(include_str!("help/topics/dml.md")),
    "doctor" => Some(include_str!("help/topics/doctor.md")),
    "drdid" => Some(include_str!("help/topics/drdid.md")),
    "drop" => Some(include_str!("help/topics/drop.md")),
    "duplicates" => Some(include_str!("help/topics/duplicates.md")),
    "elasticnet" => Some(include_str!("help/topics/elasticnet.md")),
    "encode" => Some(include_str!("help/topics/encode.md")),
    "estat" => Some(include_str!("help/topics/estat.md")),
    "estat_report" => Some(include_str!("help/topics/estat_report.md")),
    "exit" => Some(include_str!("help/topics/exit.md")),
    "export" => Some(include_str!("help/topics/export.md")),
    "generate" => Some(include_str!("help/topics/generate.md")),
    "gsort" => Some(include_str!("help/topics/gsort.md")),
    "head" => Some(include_str!("help/topics/head.md")),
    "heckman" => Some(include_str!("help/topics/heckman.md")),
    "histogram" => Some(include_str!("help/topics/histogram.md")),
    "isid" => Some(include_str!("help/topics/isid.md")),
    "ivregress" => Some(include_str!("help/topics/ivregress.md")),
    "join" => Some(include_str!("help/topics/join.md")),
    "keep" => Some(include_str!("help/topics/keep.md")),
    "label" => Some(include_str!("help/topics/label.md")),
    "lasso" => Some(include_str!("help/topics/lasso.md")),
    "logit" => Some(include_str!("help/topics/logit.md")),
    "lowess" => Some(include_str!("help/topics/lowess.md")),
    "missing" => Some(include_str!("help/topics/missing.md")),
    "nbreg" => Some(include_str!("help/topics/nbreg.md")),
    "nl" => Some(include_str!("help/topics/nl.md")),
    "panel" => Some(include_str!("help/topics/panel.md")),
    "poisson" => Some(include_str!("help/topics/poisson.md")),
    "postlasso" => Some(include_str!("help/topics/postlasso.md")),
    "predict" => Some(include_str!("help/topics/predict.md")),
    "probit" => Some(include_str!("help/topics/probit.md")),
    "qreg" => Some(include_str!("help/topics/qreg.md")),
    "quit" => Some(include_str!("help/topics/quit.md")),
    "recode" => Some(include_str!("help/topics/recode.md")),
    "regress" => Some(include_str!("help/topics/regress.md")),
    "rename" => Some(include_str!("help/topics/rename.md")),
    "replace" => Some(include_str!("help/topics/replace.md")),
    "reshape" => Some(include_str!("help/topics/reshape.md")),
    "ridge" => Some(include_str!("help/topics/ridge.md")),
    "run" => Some(include_str!("help/topics/run.md")),
    "save" => Some(include_str!("help/topics/save.md")),
    "scatter" => Some(include_str!("help/topics/scatter.md")),
    "select" => Some(include_str!("help/topics/select.md")),
    "set" => Some(include_str!("help/topics/set.md")),
    "sort" => Some(include_str!("help/topics/sort.md")),
    "spregress" => Some(include_str!("help/topics/spregress.md")),
    "sql" => Some(include_str!("help/topics/sql.md")),
    "status" => Some(include_str!("help/topics/status.md")),
    "streg" => Some(include_str!("help/topics/streg.md")),
    "summarize" => Some(include_str!("help/topics/summarize.md")),
    "tabulate" => Some(include_str!("help/topics/tabulate.md")),
    "tail" => Some(include_str!("help/topics/tail.md")),
    "tobit" => Some(include_str!("help/topics/tobit.md")),
    "use" => Some(include_str!("help/topics/use.md")),
    "xtabond" => Some(include_str!("help/topics/xtabond.md")),
    "xtdata" => Some(include_str!("help/topics/xtdata.md")),
    "xtlogit" => Some(include_str!("help/topics/xtlogit.md")),
    "xtreg" => Some(include_str!("help/topics/xtreg.md")),
    "zinb" => Some(include_str!("help/topics/zinb.md")),
    "zip" => Some(include_str!("help/topics/zip.md")),
    _ => None,
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_all_help_topics_loadable() {
    assert_eq!(available_help_topics().len(), 79);
    for topic in available_help_topics() {
      let text = load_help_topic_text(topic).expect("topic must load");
      assert!(!text.is_empty(), "topic {topic} must not be empty");
    }
  }
}
